from tests.basic.test_triangle_angle_reduction import test_triangle_angle_reduction
from tests.basic.test_triangle_sides_angle_reduction import test_triangle_sides_angle_reduction
from tests.basic.test_collineation_relationship_reduction import test_collineation_relationship_reduction

# test_triangle_angle_reduction()
# test_triangle_sides_angle_reduction()
test_collineation_relationship_reduction()
