from tests.basic.test_triangle_angle_reduction import test_triangle_angle_reduction
from tests.basic.test_triangle_sides_angle_reduction import test_triangle_sides_angle_reduction

test_triangle_sides_angle_reduction()
