from geometry_solver.relationships.relationship import Relationship
from geometry_solver.relationships.collineation import Collineation
from geometry_solver.relationships.common_vertex_angle import CommonVertexAngle
from geometry_solver.relationships.opposite_vertical_angle import OppositeVerticalAngle
from geometry_solver.relationships.supplementary_angle import SupplementaryAngle
from geometry_solver.relationships.perpendicular import Perpendicular
