from tests.simple.test_simple_example import test_simple_example
from tests.simple.test_simple_example1 import test_simple_example1
from tests.simple.test_simple_example2 import test_simple_example2
from tests.simple.test_simple_example3 import test_simple_example3
from tests.simple.test_simple_example4 import test_simple_example4
