from tests.parser.test_basic_parser import test_basic_parser
from tests.parser.test_advanced_parser import test_advanced_parser
from tests.parser.test_parser_example1 import test_parser_example1
from tests.parser.test_parser_example2 import test_parser_example2
from tests.parser.test_parser_example3 import test_parser_example3
from tests.parser.test_parser_example4 import test_parser_example4
